apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views

app_name = 'home'

urlpatterns = [

    # The home page
    path('', views.index, name='home'),

    # Matches any html file
    # re_path(r'^.*\.*', views.pages, name='pages'),

]

apps/maps/urls.py
from django.urls import path, re_path, include
from .views import InterestPointsMap, InterestPointDetailView
from .views import CreateInterestPoint, UpdateInterestPoint, CreateCamperNightPoint, UpdateCamperNightPoint

app_name = 'maps'

urlpatterns = [
    path('', InterestPointsMap.as_view(), name='home'),
    path('InterestPoint/<pk>/detail/', InterestPointDetailView.as_view(), name='InterestPointDetailView'),
    path('InterestPoint/create', CreateInterestPoint.as_view(), name='CreateInterestPoint'),
    path('InterestPoint/<pk>/update', UpdateInterestPoint.as_view(), name='UpdateInterestPoint'),

    path('CamperNightPoint/create', CreateCamperNightPoint.as_view(), name='CreateInterestPoint'),
    path('CamperNightPoint/<pk>/update', UpdateCamperNightPoint.as_view(), name='UpdateInterestPoint'),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf import settings
from django.conf.urls.static import static
from .api import api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", include("apps.authentication.urls")),  # Auth routes - login / register
    path("profile/", include("apps.home.urls")),  # UI Kits Html files
    path("", include("apps.maps.urls")),
    path("api/", api.urls),
    path('', include('pwa.urls')),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/home/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User
import os


def upload_to(instance, filename):
    print(f"****{instance}, {filename}")
    path = os.path.join('background_images/', filename)
    return path


class ImageInterestPoint(models.Model):
    title = models.CharField(max_length=210)
    image = models.ImageField(upload_to=upload_to)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

apps/maps/models.py
import os.path

from django.db import models
import uuid


def camper_night_point_upload_to(instance, filename):
    print(f"****{instance}, {filename}")
    return os.path.join('camper_night_point/', filename)


def interest_point_upload_to(instance, filename):
    print(f"****{instance}, {filename}")
    path = os.path.join('interest_point/', filename)
    return path


class Category(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=210)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class InterestPoint(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=210)
    short_description = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    category = models.ManyToManyField(Category)
    country_code = models.CharField(max_length=10, null=True, blank=True)
    country_name = models.CharField(max_length=100, null=True, blank=True)
    region = models.CharField(max_length=100, null=True, blank=True)
    region_abbr = models.CharField(max_length=10, null=True, blank=True)
    subregion = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    postal = models.CharField(max_length=10, null=True, blank=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    latitude = models.FloatField()
    longitude = models.FloatField()
    image = models.ImageField(blank=True, null=True, upload_to=interest_point_upload_to)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class CamperNightPoint(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=210)
    description = models.TextField(null=True, blank=True)
    free = models.BooleanField(default=False)
    wc = models.BooleanField(default=False)
    drinking_water = models.BooleanField(default=False)
    tables = models.BooleanField(default=False)
    gray_sink = models.BooleanField(default=False)
    black_sink = models.BooleanField(default=False)
    electricity = models.BooleanField(default=False)
    wifi = models.BooleanField(default=False)
    country_code = models.CharField(max_length=10, null=True, blank=True)
    country_name = models.CharField(max_length=100, null=True, blank=True)
    region = models.CharField(max_length=100, null=True, blank=True)
    region_abbr = models.CharField(max_length=10, null=True, blank=True)
    subregion = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    postal = models.CharField(max_length=10, null=True, blank=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    latitude = models.FloatField()
    longitude = models.FloatField()
    image = models.ImageField(blank=True, null=True, upload_to=interest_point_upload_to)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ImageInterestPoint(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    interest_point_id = models.ForeignKey(InterestPoint, on_delete=models.CASCADE)
    title = models.CharField(max_length=210)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to=interest_point_upload_to)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ImageCamperNightPoint(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    camper_night_point_id = models.ForeignKey(CamperNightPoint, on_delete=models.CASCADE)
    title = models.CharField(max_length=210)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to=camper_night_point_upload_to)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

apps/home/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse


@login_required(login_url="/login/")
def index(request):
    context = {'segment': 'index'}

    html_template = loader.get_template('home/index.html')
    return HttpResponse(html_template.render(context, request))


@login_required(login_url="/login/")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try:

        load_template = request.path.split('/')[-1]

        if load_template == 'admin':
            return HttpResponseRedirect(reverse('admin:index'))
        context['segment'] = load_template

        html_template = loader.get_template('home/' + load_template)
        return HttpResponse(html_template.render(context, request))

    except template.TemplateDoesNotExist:

        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))

    except:
        html_template = loader.get_template('home/page-500.html')
        return HttpResponse(html_template.render(context, request))

apps/maps/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy, reverse

from .models import InterestPoint, CamperNightPoint
from .models import ImageInterestPoint, ImageCamperNightPoint
from django.core.serializers import serialize
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404


class InterestPointsMap(TemplateView):
    template_name = 'maps/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['interestPoints'] = InterestPoint.objects.all()
        interest_points_data = serialize('json', context['interestPoints'])
        context['interestPoints_list'] = interest_points_data
        context['interestPointsImages'] = ImageInterestPoint.objects.distinct('interest_point_id')
        context['CamperNightPoints'] = CamperNightPoint.objects.all()
        context['CamperNightPointsImages'] = ImageCamperNightPoint.objects.all()
        return context


class InterestPointDetailView(TemplateView):
    template_name = 'maps/DetailView.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = get_object_or_404(InterestPoint, id=kwargs['pk'])
        photos = ImageInterestPoint.objects.filter(interest_point_id=post)
        context['post'] = post
        context['photos'] = photos
        return context


class CreateInterestPoint(CreateView):
    model = InterestPoint
    template_name = 'maps/CreateUpdateForm.html'
    success_url = reverse_lazy('maps:home')
    fields = '__all__'

    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(**kwargs)
        initial['name'] = 'Enter name'
        return initial

    def get_form(self, *args, **kwargs):
        form = super().get_form(**kwargs)
        exclude_fields = ['created']
        for field_name in exclude_fields:
            form.fields.pop(field_name, None)

        exclude_fields = ['category']
        for field_name, field in form.fields.items():
            if field_name not in exclude_fields:
                field.widget.attrs['class'] = 'form-control'
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Create Interest Point'
        return context


class UpdateInterestPoint(UpdateView):
    model = InterestPoint
    template_name = 'maps/CreateUpdateForm.html'
    success_url = reverse_lazy('maps:home')
    fields = '__all__'

    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(**kwargs)
        initial['name'] = 'Enter name'
        return initial

    def get_form(self, *args, **kwargs):
        form = super().get_form(**kwargs)
        exclude_fields = ['created']
        for field_name in exclude_fields:
            form.fields.pop(field_name, None)

        for field_name, field in form.fields.items():
            field.widget.attrs['class'] = 'form-control'
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Update Interest Point'
        return context


class CreateCamperNightPoint(CreateView):
    model = CamperNightPoint
    template_name = 'maps/CreateUpdateForm.html'
    success_url = reverse_lazy('maps:home')
    fields = '__all__'

    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(**kwargs)
        initial['name'] = 'Enter name'
        return initial

    def get_form(self, *args, **kwargs):
        form = super().get_form(**kwargs)
        exclude_fields = ['created']
        for field_name in exclude_fields:
            form.fields.pop(field_name, None)

        exclude_fields = ['free', 'wc', 'drinking_water', 'tables',
                          'gray_sink', 'black_sink', 'electricity',
                          'wifi']
        for field_name, field in form.fields.items():
            if field_name not in exclude_fields:
                field.widget.attrs['class'] = 'form-control'
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Create Camper Night Point'
        return context


class UpdateCamperNightPoint(UpdateView):
    model = CamperNightPoint
    template_name = 'maps/CreateUpdateForm.html'
    success_url = reverse_lazy('maps:home')
    fields = '__all__'

    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(**kwargs)
        initial['name'] = 'Enter name'
        return initial

    def get_form(self, *args, **kwargs):
        form = super().get_form(**kwargs)
        exclude_fields = ['created']
        for field_name in exclude_fields:
            form.fields.pop(field_name, None)

        for field_name, field in form.fields.items():
            field.widget.attrs['class'] = 'form-control'
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Update Camper Night Point'
        return context

apps/templates/maps/CreateUpdateForm.html
{% extends 'maps/base.html' %}

{% load static %}
{% load i18n %}


{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <h2>{{ form_title }}</h2>
        {{ form.as_div }}
        <input type="submit" class="btn btn-primary mt-2 md-2" value="Save">
    </form>
</div>

{% endblock %}

apps/templates/maps/DetailView.html
{% extends 'maps/base.html' %}

{% load static %}
{% load i18n %}

{% block content %}
{% include "maps/leaflet.html" %}

<style>
#map {
    height: 90vh;
    border-radius: 5px;
    font-size: 0px; // para esconder la palabra leaflet
    //top: 5px;
    //bottom: 5px;
    //left: 5px;
    //margin-right: 0px;
}
</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


<div class="container-fluid">
    <div class="row mt-2 mb-2">
        <div class="col-md-6 col-sm-12 mb-2">
            <div id="carousel-images" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
            {% for img_point in photos %}
            <div class="carousel-item {% if forloop.first %} active {% endif %}">
                <img class="d-block w-100" src="{{ img_point.image.url }}" alt="Card image cap" style="max-height: 60vh; object-fit: cover;">
            </div>
            {% endfor %}

            </div>
            <a class="carousel-control-prev" href="#carousel-images" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-images" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <h5>{{ post.title }}</h5>
            <p>{{ post.description }}</p>
            <p>
                <small class="text-muted">Categories:
                {% for category in post.category.all %}
                    {{ category.name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
                </small>
            </p>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
       $('#carousel-images').carousel();
    });
</script>
<script>
    var zoom_map = 6;
    var latitude = 40.078774770944534;
    var longitude = -3.7004158795299302;
    var markersSearch = new L.markerClusterGroup();
    var markersInterestPoint = new L.markerClusterGroup();
    var markersCamperNightPoint = new L.markerClusterGroup();
    var click_mark = new L.markerClusterGroup();
    var circle = new L.circle();
    var overlayMaps = {};
</script>
<script type="text/javascript" src="{% static 'js/main_leaflet.js' %}"></script>
<script type="text/javascript" src="{% static 'js/locationfound.js' %}"></script>
<script type="text/javascript" src="{% static 'js/mapClick.js' %}"></script>
<script  type="text/javascript">
    var first_time_location = 0;
    map.on('locationfound', function (e) {
        console.log("first_time_location 0", first_time_location);
        if (first_time_location == 0) {
        console.log("first_time_location 1", first_time_location);
        console.log('Location found:', e);
        var km = 150;
        var km2m = km * 1000;
        circle = new L.circle(e.latlng, km2m).setStyle({color: 'green'}).addTo(map);
        var circleBounds = circle.getBounds();
        var combinedBounds = L.latLngBounds(circleBounds.getSouthWest(), circleBounds.getNorthEast());
        combinedBounds.extend(e.latlng);
        console.log("combinedBounds", combinedBounds);
        map.fitBounds(combinedBounds);
        {% for points in interestPoints %}
            var longitude = "{{ points.longitude }}";
            var latitude = "{{ points.latitude }}";
            var longitude = parseFloat(longitude.replace(",", "."));
            var latitude = parseFloat(latitude.replace(",", "."));
            var fromLatLng = new L.LatLng(e.latlng['lat'], e.latlng['lng']);
            var toLatLng = new L.latLng(latitude, longitude);
            var distance_geo = fromLatLng.distanceTo(toLatLng)/1000;
            if (distance_geo < km2m){
                markersInterestPoint.addLayer(L.marker([latitude, longitude])).bindPopup();
                map.addLayer(markersInterestPoint);
            }
        {% endfor %}
        {% for points in CamperNightPoints %}
            var longitude = "{{ points.longitude }}";
            var latitude = "{{ points.latitude }}";
            var longitude = parseFloat(longitude.replace(",", "."));
            var latitude = parseFloat(latitude.replace(",", "."));
            var fromLatLng = new L.LatLng(e.latlng['lat'], e.latlng['lng']);
            var toLatLng = new L.latLng(latitude, longitude);
            var distance_geo = fromLatLng.distanceTo(toLatLng)/1000;
            if (distance_geo < km2m){
                markersCamperNightPoint.addLayer(L.marker([latitude, longitude])).bindPopup();
                map.addLayer(markersCamperNightPoint);
            }
        {% endfor %}
        }
        overlayMaps['interest'] = markersInterestPoint;
        overlayMaps['night'] = markersCamperNightPoint;
        L.control.layers(baseMaps, overlayMaps, { collapsed: true }).addTo(map);
        first_time_location = first_time_location + 1;
});

</script>
{% endblock %}

apps/templates/maps/base.html
<!doctype html>
<html lang="eu">

<head>
    {% load pwa %}
    {% pwa_meta_data %}
    {% pwa_meta_script %}

    {% load static %}
    {% load i18n %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content="Euskal Herriko eskaladako krosikak ikusteko webgunea"/>
    <meta name="keywords" content="Eskalada, Euskal Herria, Krokisak, Eguraldia, Eskalada ikastaroak"/>
    <meta name="author" content="mundubertikala@gmail.com"/>
    <meta property="og:title" content="Croquis de escalada, Eskaladako krokisak"/>
    <meta property="og:image" content="{% static 'images/main.jpg' %}"/>
    <meta property="og:description" content="Eskaladako krosikak ikusteko webgunea"/>
    <meta property="og:url" content="https://mundubertikala.eus"/>
    <meta property=”og:type” content="website"/>
    <meta property="og:site_name" content="Mundu bertikala" />
    <script type="application/ld+json">
    {
        "@context": "https://schema.org/",
        "@type": "WebSite",
        "name": "Mundu bertikala",
        "url": "https://mundubertikala.eus",
        "description": "",
        "image": "{% static 'images/main.jpg' %}",
        "potentialAction": {
            "@type": "SearchAction",
            "target": "https://mundubertikala.eus/eguraldia/"
        }
    }
    </script>


    <link rel="icon" type="image/x-icon" href="media/images/favicon.ico">
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="navbar.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>



    <!-- Global site tag (gtag.js) - Google Analytics
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-RME206CNR5"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-RME206CNR5');

    </script>
    -->
    <title>{% block title %}{% endblock %} | TxatxiLife</title>
    <style>
<!--        header {-->
<!--          position: fixed;-->
<!--          left: 0px;-->
<!--          right: 0px;-->
<!--          z-index: 1;-->
<!--        }-->
        footer {
          //position: fixed;
          text-align: center;
          padding-top: 5px;
          padding-bottom: 1px;
          background-color: black;
          color: white;
          left: 0px;
          right: 0px;
          margin-bottom: 0px;
          margin-top: 0;
          bottom: 0px;
          //border-top: 10px solid red;
        }
    </style>
</head>

<header class="p-3 bg-dark text-white">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home:home' %}" style="font-family:verdana">
            <img src="/media/icons/logo1.png" height="100px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if request.user.username == 'admin' %}<li class="nav-item"><a style="font-family:verdana" href="#" class="nav-link px-2 text-white">admin_tool</a></li>{% endif %}
                <li class="nav-item"><a style="font-family:verdana" href="#" class="nav-link px-2 text-white">Euskalmet</a></li>
                <li class="nav-item"><a style="font-family:verdana" href="#" class="nav-link px-2 text-white">{% trans "Kontaktua" %}</a></li>
            </ul>
            <ul class="navbar-nav navbar-right ml-auto">
              {% if not request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" style="font-family:verdana" href="#">{% trans 'Nire gunea' %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" style="font-family:verdana" href="#">{% trans 'Izena eman' %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" style="font-family:verdana" href="#">{% trans 'Ongi etorri' %} <b style="color:white;">{{ request.user }}</b></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" style="font-family:verdana" href="{% url 'account_logout' %}">{% trans 'Irten' %}</a>
                </li>
              {% endif %}
            </ul>
            {% get_current_language as CURRENT_LANGUAGE %}
            {% get_available_languages as AVAILABLE_LANGUAGES %}
            {% get_language_info_list for AVAILABLE_LANGUAGES as languages %}

            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ CURRENT_LANGUAGE }}
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  {% for language in languages %}
                    <a class="dropdown-item" href="/{{ language.code }}/{{ request.get_full_path|slice:'4:' }}">{{ language.code }}</a>
                  {% endfor %}
              </div>
            </div>
        </div>
    </nav>
</header>

<body>
{% block content %} {% endblock %}
</body>
<!-- Footer -->
<footer>
    <a id="blink" href="https://www.paypal.com/donate/?hosted_button_id=A69Z63Q2F22E2" class="btn btn-warning">{% trans 'Dohaintza egin' %}</a>
    <ul class="nav justify-content-center">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Txatxilife</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">{% trans 'Lege Oharra' %}</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">{% trans 'Cookiei buruzko oharra' %}</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">{% trans 'Datuen Babeserako politika' %}</a></li>
    </ul>
    <p class="text-center text-muted">&copy; 2024 Txatxilife </p>
</footer>



<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->

</html>